### ISSUE TITLE
Support for sorting JSON

### ISSUE THREAD

**Issue by marc-barry** [bai/doggy#14]
The Datadog API returns JSON keys in different order making checking for changes with `doggy pull` very hard when you have a lot of dashboards, monitors and screens. Support for sorting of the JSON is needed so that when the JSON doesn't change, and only the orders does, that we don't see a change from Git's perspective.

Note that I have even seen that pulling the same object more then once results in differently ordered JSON coming from the Datadog API.

**Comment by ElvinEfendi** [comment]
I think the source of problem is actually sorting - doggy already sorts JSON keys before saving the objects. To fix the problem we should get rid of sorting and just save objects as they come from Datadog API.

**Comment by marc-barry** [comment]
This will be fixed by #17.
