### ISSUE TITLE
Required Ruby Version

### ISSUE THREAD

**Issue by eapache** [bai/doggy#4]
Doggy requires ruby 2.1 or later because it uses required keyword arguments (https://github.com/bai/doggy/blob/a850c75ab1158aa52fdb1ce6cae8e694914d71e8/lib/doggy/cli/pull.rb#L5)

It would be convenient if the gemspec listed this using the `required_ruby_version` stanza.

**Comment by bai** [comment]
Downgraded to 2.0 and fixed in https://github.com/bai/doggy/commit/9da4e3c8111398bc1e92024813001d151ae56066
