### ISSUE TITLE
Support `doggy edit FILENAME`

### ISSUE THREAD

**Issue by wvanbergen** [bai/doggy#5]
Now objects can have nice filenames, it would be nice if you can refer to these filenames instead of IDs.

**Comment by bai** [comment]
It's supported as `bundle exec doggy edit sigint/monitor-heka-processing.json`. Let me know if that doesn't work for you.

I'll update the docs to make sure this usecase is clear.

**Comment by wvanbergen** [comment]
I noticed `doggy edit folder/name.json` works, but `doggy edit objects/folder/name.json` doesn't. It would be nice if that is also supported so I can use tab completion in my shell.

**Comment by wvanbergen** [comment]
What would also be nice:

```
bundle exec doggy edit "https://app.datadoghq.com/dash/dash/1234"
```

This way, when I am looking at a dashboard and I want to change it, I can just copy paste the URL.

**Comment by bai** [comment]
@wvanbergen added URL editing in https://github.com/bai/doggy/commit/4f87ebbaf085afa32443c276d034f41114102c60

**Comment by wvanbergen** [comment]
:clap: - Can you also make `doggy edit `objects/file.json` work (besides `doggy edit file.json`) for my tab completion sanity?
